services:
  # PostgreSQL 데이터 베이스 서비스
  postgres:
    image: postgres:17
    container_name: discodeit-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - "5432:5432"
    volumes:
      # PostgreSQL 데이터 볼륨 (데이터 영속성)
      - postgres_data:/var/lib/postgresql/data
      # 스키마 초기화 스크립트
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    networks:
      - discodeit-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # 애플리케이션 서비스
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discodeit-app
    environment:
      # Spring 프로필 설정
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}

      # 데이터베이스 연결 설정
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}

      # 서버 설정
      SERVER_PORT: ${SERVER_PORT}

      # Storage 설정
      STORAGE_TYPE: ${STORAGE_TYPE:-local}
      STORAGE_LOCAL_ROOT_PATH: ${STORAGE_LOCAL_ROOT_PATH:-.discodeit/storage}

      # AWS S3 설정
      AWS_S3_ACCESS_KEY: ${AWS_S3_ACCESS_KEY}
      AWS_S3_SECRET_KEY: ${AWS_S3_SECRET_KEY}
      AWS_S3_REGION: ${AWS_S3_REGION:-ap-northeast-2}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      AWS_S3_PRESIGNED_URL_EXPIRATION: ${AWS_S3_PRESIGNED_URL_EXPIRATION:-600}


      # JVM 옵션
      JVM_OPTS: ${JVM_OPTS}
    ports:
      - "8081:80"
    volumes:
      # BinaryContentStorage 데이터 볼륨 (파일 업로드 데이터 영속성)
      - app_storage:/app/.discodeit/storage
    networks:
      - discodeit-network
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

# 볼륨 정의
volumes:
  # PostgreSQL 데이터 영속성 복륨
  postgres_data:
    driver: local
  # 애플리케이션 스토리지 영속성 볼륨
  app_storage:
    driver: local

# 네트워크 정의
networks:
  discodeit-network:
    driver: bridge