spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        default_schema: discodeit

logging:
  level:
    root: INFO
    org.springframework: DEBUG

# JWT 설정
jwt:
  access-token:
    secret: 5mB1dfWfn8ygrUjaY31ZFhZi6KzfX_7uOj6ae9IubC0
    exp: 900000 # 15분
  refresh-token:
    secret: lqmmP_B1CxhpP4g-z5y5Rco34uYbY0is4nJRdYRRtHk
    exp: 3600000 # 1시간
