spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

server:
  port: 8081

logging:
  level:
    com.sprint.mission.discodeit: DEBUG
    org.springframework.security: TRACE

# JWT 설정
jwt:
  access-token:
    secret: 5mB1dfWfn8ygrUjaY31ZFhZi6KzfX_7uOj6ae9IubC0
    exp: 900000 # 15분
  refresh-token:
    secret: lqmmP_B1CxhpP4g-z5y5Rco34uYbY0is4nJRdYRRtHk
    exp: 3600000 # 1시간
