spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:discodeit_user}
    password: ${SPRING_DATASOURCE_PASSWORD:discodeit1234}

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081

logging:
  level:
    root: info
    com.sprint.mission: debug
    org.springframework.security: trace
    # Spring Cache 관련 디버그 로그 활성화 (캐시 Hit/Miss 추적)
    org.springframework.cache: debug
    org.springframework.cache.interceptor: trace
