spring:
  cache:
    caffeine:
      spec: >
        maximumSize=100,
        expireAfterAccess=600s,
        recordStats

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, loggers, caches
  endpoint:
    info:
      enabled: true
    caches:
      enabled: true
    health:
      show-details: always
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
  observations:
    annotations:
      enabled: true

discodeit:
  storage:
    type: ${STORAGE_TYPE:local}
    local:
      root-path: ${STORAGE_LOCAL_ROOT_PATH:./binaries}
    s3:
      access-key: ${AWS_S3_ACCESS_KEY}
      secret-key: ${AWS_S3_SECRET_KEY}
      region: ${AWS_S3_REGION}
      bucket: ${AWS_S3_BUCKET}
      presigned-url-expiration: ${AWS_S3_PRESIGNED_URL_EXPIRATION:600}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    operations-sorter: method

info:
  app:
    name: Discodeit
    version: 1.7.0
    java:
      version: 17
    spring-boot:
      version: 3.4.0

logging:
  level:
    com.sprint.mission.discodeit: INFO
    org.hibernate.sql: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

admin:
  username: ${ADMIN_USERNAME:admin}
  email: ${ADMIN_EMAIL:admin@admin.com}
  password: ${ADMIN_PASSWORD:admin1234}

async:
  executors:
    binary-content:
      core-size: ${MAX_CORE_SIZE:4}
      max-size: ${MAX_SIZE:8}
      queue-capacity: ${QUEUE_CAPACITY:200}
      keep-alive: ${KEEP_ALIVE:60}
    notification:
      core-size: ${MAX_CORE_SIZE:2}
      max-size: ${MAX_SIZE:4}
      queue-capacity: ${QUEUE_CAPACITY:100}
      keep-alive: ${KEEP_ALIVE:30}