spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        ddl-auto: create-drop

logging:
  level:
    root: INFO
    org.springframework: DEBUG