#spring.application.name=discodeit
discodeit:
  storage:
    type: local
    local:
      root-path: ./storage
    repository:
      file-directory: .discodeit

server:
  port: 8080

logging:
  config: classpath:logback-spring.xml
  level:
    org.hibernate.sql: debug
    org.hibernate.orm.jdbc.bind: trace
    com.sprint.mission.discodeit: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss:SSS} [%thread] %-5level [%X{traceId}] %logger{36} - %msg%n"

spring:
  application:
    name: discodeit
  servlet:
    multipart:
      maxFileSize: 10MB # 파일 하나의 최대 크기
      maxRequestSize: 30MB  # 한 번에 최대 업로드 가능 용량
  profiles:
    active: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/discodeit
    username: discodeit_user
    password: discodeit1234
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        ddl-auto: update
        show_sql: false
    open-in-view: false

jdbc:
  time_zone: UTC

springdoc:
  api-docs:
    # OpenAPI 명세서 경로(JSON) -> 기억해두자!!! 미션 때 써먹어야됨.
    #    path: /hi/my/name/is
    path: /v3/api-docs
    title:
  swagger-ui:
    # Swagger-ui 경로(HTML)
    path: /my-swagger-ui.html
    # API 정렬 기준 - HTTP 메서드의 알파벳순
    operations-sorter: method