#spring.application.name=discodeit
server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/discodeit
    username: discodeit_user
    password: discodeit1234
    #    driver-class-name: org.postgresql.Driver

    hikari:
      connection-init-sql: SET SESSION hibernate.jdbc.lob.non_contextual_creation=true

    jpa:
      generate-ddl: false
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      properties:
        hibernate:
          format_sql: true
          highlight_sql: true
          use_sql_comments: true
          ddl-auto: update
      open-in-view: true

    logging:
      level:
        org.hibernate.sql: debug
        org.hibernate.orm.jdbc.bind: trace

  application:
    name: discodeit

jdbc:
  time_zone: UTC

discodeit:
  storage:
    type: local
    local:
      root-path: ./storage

springdoc:
  api-docs:
    # OpenAPI 명세서 경로(JSON) -> 기억해두자!!! 미션 때 써먹어야됨.
    #    path: /hi/my/name/is
    path: /v3/api-docs
    title:
  swagger-ui:
    # Swagger-ui 경로(HTML)
    path: /my-swagger-ui.html
    # API 정렬 기준 - HTTP 메서드의 알파벳순
    operations-sorter: method