# FIXME : openAPI -> postman 으로 import 잘 안됨.

openapi: 3.0.0
info:
  title: sprint-mission-4
  description: ' sprint mission4 API 요청 모음'
  version: 1.0.0
servers:
  - url: http://{{baseurl}}
paths:
  #  유저 생성
  /api/users:
    post:
      tags:
        - default
      summary: /api/users 유저 생성
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                userCreateRequest:
                  type: string
                  example: >-
                    { "name" : "케이트", "email":"케이트123@naver.com",
                    "password":"123" }
                profile:
                  type: string
                  format: binary
      responses:
        '200':
          description: Successful response
          content:
            application/json: { }
    #  유저 전체 조회
    get:
      tags:
        - default
      summary: /api/users 유저 전체 조회
      responses:
        '200':
          description: Successful response
          content:
            application/json: { }
    #  유저 로그인
  /api/auth/login:
    post:
      tags:
        - default
      summary: /api/auth/login 로그인
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: 케이트123@naver.com
                password: '1234'
      responses:
        '200':
          description: Successful response
          content:
            application/json: { }
    #  유저 삭제
  /api/users/28004ab9-aa7a-41e6-92bd-27c0b936d385:
    delete:
      tags:
        - default
      summary: /api/users 유저 삭제
      responses:
        '200':
          description: Successful response
          content:
            application/json: { }
    #  유저 상태 업데이트
  /api/user-status/309142bf-b16c-4e94-9597-8e87925aa0bb:
    put:
      tags:
        - default
      summary: /api/status 상태 업데이트
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  example: "DND"  # 예시값을 "DND"로 설정
      responses:
        '200':
          description: Successful response
          content:
            application/json: { }
    #  공개 채널 생성
  /api/channels/public:
    post:
      tags:
        - default
      summary: /api/channels/public 공개 채널 생성
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: '공개채널입니다'
                description: "공개채널 설명"
                ownerId: '309142bf-b16c-4e94-9597-8e87925aa0bb'
      responses:
        '200':
          description: Successful response
          content:
            application/json: { }
    #  비공개 채널 생성
  /api/channels/private:
    post:
      tags:
        - default
      summary: /api/channels/private 비공개 채널 생성
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                ownerId: '309142bf-b16c-4e94-9597-8e87925aa0bb'
                participantIds:
      responses:
        '200':
          description: Successful response
          content:
            application/json: { }
    #  공개 채널 수정
  /api/channels/public/1234:
    put:
      tags:
        - default
      summary: /api/channels/public 공개 채널 수정
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                newName: '새로운 공개채널이름 '
                newDescription: "새로운 공개채널 설명"
      responses:
        '200':
          description: Successful response
          content:
            application/json: { }
    #  채널 삭제
  /api/channels/28004ab9-aa7a-41e6-92bd-27c0b936d385:
    delete:
      tags:
        - default
      summary: /api/channels/ 채널 삭제
      responses:
        '200':
          description: Successful response
          content:
            application/json: { }
  #   특정 사용자가 볼 수 있는 모든 채널 목록 조회
  /api/channels/123userId4:
    delete:
      tags:
        - default
      summary: /api/channels/ 특정 사용자가 볼 수 있는 모든 채널 목록 조회
      responses:
        '200':
          description: Successful response
          content:
            application/json: { }