server:
  port: 8080

spring:
  application:
    name: discodeit
  survlet:
    multipart:
      max-file-size: 10MB

  logging:
    level:
      root: info

spring-doc:
  api-docs:
    # OpenAPI 명세서 경로(JSON)
    path: /api-docs
  swagger-ui:
    # OpenAPI 명세서 경로(HTML)
    path: /swagger-ui.html


  repository:
    type: file   # jcf | file
    user-file-path: .files/User.json
    channel-file-path: .files/Channel.json
    message-file-path: .files/Message.json
    user-status-file-path: .files/UserStatus.json
    read-status-file-path: .files/ReadStatus.json
    binary-content-file-path: .files/BinaryContent.json
