name: Test AWS (CI)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: '17'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      # 선택: Gradle 캐시(속도 향상)
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 권한 문제 예방 (과거에 permission denied 경험 있었으면 필수)
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # AWS CLI 동작 확인
      - name: Test AWS CLI (STS caller identity)
        run: aws sts get-caller-identity

      - name: Describe ECR Public repository
        run: |
          aws ecr-public describe-repositories \
            --repository-names "${{ secrets.ECR_REPOSITORY }}" \
            --region us-east-1


      - name: Run tests & generate JaCoCo report
        run: ./gradlew test jacocoTestReport

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: bladnoch/3-sprint-mission
          fail_ci_if_error: true
